In [1]:
import pandas as pd
import numpy as np

In [2]:
my_data = pd.read_csv("E:/Dataset/IRIS.csv")
my_data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
species_names = my_data['species'].unique()
species_names

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
my_data['species'] =  label.fit_transform(my_data['species'])

In [12]:
my_data.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [13]:
species_number = my_data['species'].unique()
pd.DataFrame({"Names":species_names,"Encoded_names":species_number})

Names  Encoded_names
0      Iris-setosa              0
1  Iris-versicolor              1
2   Iris-virginica              2

In [14]:
x = my_data.iloc[:,:-1].values
y = my_data.iloc[:,-1].values
x,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,stratify=y)

In [16]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((105, 4), (105,), (45, 4), (45,))

In [17]:
from sklearn.linear_model import LinearRegression, LogisticRegression

In [18]:
model = LinearRegression()

In [19]:
model.fit(x_train,y_train)

LinearRegression()

In [28]:
ans = model.predict(x_test)

In [29]:
ans

array([ 1.75799228e+00,  1.50080399e-01, -2.21717935e-02, -1.16333202e-01,
       -7.59570525e-02, -7.51253068e-02,  1.52928006e+00,  1.92805301e+00,
        9.14907809e-01,  1.30756724e+00,  2.12414147e+00,  1.73871891e+00,
        1.47236098e+00,  1.85903039e+00,  1.60764515e-03,  1.19371772e+00,
        9.55803701e-04,  1.17569120e+00, -2.22184925e-01,  1.39295288e+00,
        1.34723740e+00,  2.20610047e+00, -3.49495778e-03, -9.65894126e-02,
        2.07391992e+00,  1.40285243e+00,  1.28871050e+00, -1.06488959e-01,
        1.20249464e+00,  1.40956322e+00, -9.68246207e-02,  8.93915641e-01,
        9.27719227e-01,  1.19864041e+00, -6.18419524e-02,  1.93214433e+00,
       -2.11601436e-02,  1.61484371e+00,  1.33402298e+00,  1.80287565e+00,
        1.96813901e+00,  2.19274782e+00,  1.80281919e+00,  1.29386878e+00,
       -3.43881941e-02])

In [30]:
ans = (ans>0.5)

In [31]:
ans

array([ True, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False])

In [26]:
ans = ans.astype('int')

In [27]:
ans

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0])

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(ans,y_test)

array([[15,  0,  0],
       [ 0, 15, 15],
       [ 0,  0,  0]], dtype=int64)

In [37]:
accuracy_score(ans,y_test)*100

66.66666666666666

In [38]:
new_data = pd.read_csv('E:/Dataset/P14-Simple-Linear-Regression/Simple_Linear_Regression/Salary_Data.csv')
new_data.head()

Years  Salary
0    1.1   39343
1    1.3   46205
2    1.5   37731
3    2.0   43525
4    2.2   39891

In [39]:
inp = new_data.iloc[:,0].values
oup = new_data.iloc[:,1].values

In [45]:
inp.reshape(-1,1).shape,oup.shape

((30, 1), (30,))

In [46]:
x_train,x_test,y_train,y_test = train_test_split(inp.reshape(-1,1),oup,test_size=0.3)

In [47]:
model.fit(x_train,y_train)

LinearRegression()

In [48]:
ans = model.predict(x_test)

In [49]:
pd.DataFrame({"predict":ans,"actual Y":y_test})

predict  actual Y
0   75833.669503     83088
1   47064.500864     39891
2   53560.764750     56642
3  102746.762745    113812
4   40568.236978     37731
5   54488.802448     60150
6   60985.066334     57189
7   68409.367919     61111
8  110171.064329    105582

In [51]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
mean_squared_error(ans,y_test),mean_absolute_error(ans,y_test)

(40539198.720284656, 5861.804108679767)